### ISSUE TITLE
Add cmake support

### ISSUE THREAD

**Issue by ElTh0r0** [inyokaproject/inyokaedit#110]
Not necessarily needed with Qt 6, but nice to have cmake support in future

**Comment by KaiserBarbarossa** [comment]
Maybe [this](https://code.qt.io/cgit/qt/qtbase.git/tree/util/cmake?h=6.0) could help. I could try it in the next few days ;)

**Comment by ElTh0r0** [comment]
Hi @KaiserBarbarossa 
any help is appreciated, since I didn't work with cmake so far! I really don't know, if this is an easy task or maybe quite complex due to all the nested checks in application.pro
Luckily this task is not urgent since qmake is still supported with Qt 6
