### ISSUE TITLE
Embedding Inyoka python code in InyokaEdit

### ISSUE THREAD

**Issue by ElTh0r0** [inyokaproject/inyokaedit#93]
By using Python/C++ API it might be possible to use the original Inyoka source (parser / template language) in InyokaEdit.

API Reference: http://docs.python.org/c-api/
Example {de}: http://python.haas.homelinux.net/python_kapitel_26_003.htm#mjc6b49d1c4e0ceb18304013caf898a2e0

**Comment by encbladexp** [comment]
In a perfect world, somebody would write a new parser in Rust. The Parser is atm the slowest part of Inyoka, and depends on some parts on an existing database and Jinja.

**Comment by ElTh0r0** [comment]
Following encbladexp's comment, Inyoka code cannot be embedded for parsing the template language --> won't be implemented. Only solution is #17
